[package]
name = "yams"
version = "0.1.0"
authors = ["Alex Addy <alex.addy@gmail.com>"]
edition = "2018"

[dependencies]
warp = { version = "0.3" }
tokio = { version = "1", features = ["full"] }

comrak = "0.2.5"

git2 = "0.7"
json = "0.11"
failure = "0.1"
chrono = "0.4"

